"""Core infrastructure utilities."""

from app.core.cache import RedisCache, get_cache
from app.core.enums import (
    ALL_PERMISSIONS,
    RBAC_PERMISSIONS,
    AnalysisStatus,
    AuditAction,
    DocumentStatus,
    IncidentCategory,
    IncidentSeverity,
    IncidentStatus,
    NotificationChannel,
    NotificationStatus,
    RoleName,
    expand_role_permissions,
    role_has_permission,
)
from app.core.exceptions import (
    AppException,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    DatabaseError,
    ExternalServiceError,
    KafkaError,
    LLMError,
    NotFoundError,
    RateLimitError,
    ServiceUnavailableError,
    StorageError,
    ValidationError,
    VectorStoreError,
)
from app.core.kafka import KafkaConsumerWorker, KafkaProducer, get_kafka_producer
from app.core.logging import bind_request_context, clear_request_context, get_logger, setup_logging
from app.core.repository import BaseRepository
from app.core.security import (
    create_access_token,
    create_refresh_token,
    decode_access_token,
    decode_refresh_token,
    decode_token,
    generate_api_key,
    hash_api_key,
    hash_password,
    hash_refresh_token,
    sanitize_prompt_input,
    verify_api_key,
    verify_password,
)
from app.core.storage import ObjectStorage, get_object_storage

__all__ = [
    "ALL_PERMISSIONS",
    "RBAC_PERMISSIONS",
    "AnalysisStatus",
    "AppException",
    "AuditAction",
    "AuthenticationError",
    "AuthorizationError",
    "BaseRepository",
    "ConflictError",
    "DatabaseError",
    "DocumentStatus",
    "ExternalServiceError",
    "IncidentCategory",
    "IncidentSeverity",
    "IncidentStatus",
    "KafkaConsumerWorker",
    "KafkaError",
    "KafkaProducer",
    "LLMError",
    "NotFoundError",
    "NotificationChannel",
    "NotificationStatus",
    "ObjectStorage",
    "RateLimitError",
    "RedisCache",
    "RoleName",
    "ServiceUnavailableError",
    "StorageError",
    "ValidationError",
    "VectorStoreError",
    "bind_request_context",
    "clear_request_context",
    "create_access_token",
    "create_refresh_token",
    "decode_access_token",
    "decode_refresh_token",
    "decode_token",
    "expand_role_permissions",
    "generate_api_key",
    "get_cache",
    "get_kafka_producer",
    "get_logger",
    "get_object_storage",
    "hash_api_key",
    "hash_password",
    "hash_refresh_token",
    "role_has_permission",
    "sanitize_prompt_input",
    "setup_logging",
    "verify_api_key",
    "verify_password",
]
